name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.CD_GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.CD_GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Cloud SDK with GKE authentication plugin
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: project-42aa52a6-0cc6-4d7b-863
        install_components: gke-gcloud-auth-plugin

    - name: Configure Docker for GAR
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="us-central1-docker.pkg.dev/project-42aa52a6-0cc6-4d7b-863/oppe2-repo/oppe2-api:latest"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Verify GKE authentication plugin
      run: gke-gcloud-auth-plugin --version

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials oppe2-cluster --zone us-central1-a --project project-42aa52a6-0cc6-4d7b-863

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/hpa.yaml
        kubectl rollout restart deployment/heart-disease-api
